# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 15:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=15)),
                ('post', models.TextField()),
                ('date', models.DateTimeField(default='')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('college', models.CharField(blank=True, max_length=150, null=True)),
                ('highlight', models.CharField(blank=True, max_length=150, null=True)),
                ('subjects', models.CharField(blank=True, max_length=150, null=True)),
                ('stream', models.CharField(blank=True, max_length=150, null=True)),
                ('projects', models.CharField(blank=True, max_length=150, null=True)),
                ('internship', models.CharField(blank=True, max_length=150, null=True)),
                ('hobbies', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
