# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_onetimelinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='profile', upload_to='profile_pic'),
        ),
    ]
