# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20171221_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='By_name',
            field=models.CharField(default='user', max_length=150),
        ),
        migrations.AddField(
            model_name='requests',
            name='to_name',
            field=models.CharField(default='user', max_length=150),
        ),
    ]
