# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20171222_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='requested_by',
            new_name='requested_by_id',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='requested_to',
            new_name='requested_to_id',
        ),
    ]
