# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20171222_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='name',
            field=models.CharField(default='name', max_length=150),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.TextField(max_length=150),
        ),
    ]
