# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='date',
        ),
    ]
