# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20171228_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='date',
            field=models.DateTimeField(default='1999-01-01 01:01:01'),
        ),
    ]
