# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20171229_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default='1999-01-01 01:01:01'),
        ),
    ]
